version: '3'

# Задачи для работы с проектом
tasks:
  
  init:
    desc: "🚀 Инициализация проекта - установка зависимостей"
    cmds:
      - echo "Устанавливаем зависимости с помощью uv..."
      - uv sync
      - echo "✅ Проект готов к работе!"

  # Тестирование
  
  test:
    desc: "🧪 Запуск всех тестов проекта"
    cmds:
      - uv run pytest -v --tb=short

  test:strings:
    desc: "🔤 Тесты заданий по строкам (1_strings)"
    cmds:
      - uv run pytest 1_strings/ -v --tb=short

  test:dicts:
    desc: "📚 Тесты заданий по словарям (2_dicts)" 
    cmds:
      - uv run pytest 2_dicts/ -v --tb=short

  test:functions:
    desc: "⚙️ Тесты заданий по функциям (3_functions)"
    cmds:
      - uv run pytest 3_functions/ -v --tb=short

  test:decorators:
    desc: "🎭 Тесты заданий по декораторам (4_decorators)"
    cmds:
      - uv run pytest 4_decorators/ -v --tb=short

  test:iterators:
    desc: "🔄 Тесты заданий по итераторам (5_iterators)"
    cmds:
      - uv run pytest 5_iterators/ -v --tb=short

  test:classes:
    desc: "🏛️ Тесты заданий по классам (6_classes)"
    cmds:
      - uv run pytest 6_classes/ -v --tb=short

  test:final:
    desc: "🎯 Тесты финального задания (7_final_task)"
    cmds:
      - echo "Финальное задание пока не содержит автоматизированных тестов"
      - echo "См. описание в 7_final_task/weather_task.md"

  # Проверка качества кода

  lint:
    desc: "🔍 Проверка кода линтером"
    cmds:
      - uv run ruff check .

  format:
    desc: "✨ Автоматическое форматирование кода"
    cmds:
      - uv run ruff format .

  check:
    desc: "🔍 Полная проверка кода (линтер + форматирование)"
    cmds:
      - uv run ruff check .
      - uv run ruff format --check .

  default:
    desc: "📋 Показать справку"
    cmds:
      - echo "=== 🎓 Основные команды ==="
      - echo "task init           - Настроить проект"
      - echo "task test           - Запустить все тесты"
      - echo "task test:strings   - Тесты по строкам"
      - echo "task test:dicts     - Тесты по словарям"
      - echo "task test:functions - Тесты по функциям"
      - echo "task lint           - Проверка линтером"
      - echo "task format         - Форматирование кода"
      - echo "task check          - Полная проверка"
      - echo ""
      - echo "Документация ./docs/"